### ISSUE TITLE
Project Estimation (Update)

### ISSUE THREAD

**Issue by Joshuahozy1** [Joshuahozy1/ICT2201_P5-4#109]

**Comment by Joshuahozy1** [comment]
Updated UUCW, TCF, EF and UCP based on use case changes.
Transactions were recalculated.

UPDATES to Project Estimation
use cases recalculation after recalculating all transactions
UUCW: 125

Actor
no change
Simple - 0
Medium - 0
complex - 3 (DB, Allocation manager, Staff)
Total: 9

WCS
Changes:
distributed system - assesment 0 (As no distributed system)
end user training - assesment 5 (As not IT sevvy)
TCF - 0.965

EFactor
EF = 0.815


UCP = 125 * 0.965 * 0.815 = 98.309375

**Comment by 2robinxx** [comment]
Made changes to the Project Estimation.

UCP = 158

Effort estimation = 2,370 Hours to 4,740 Hours

Individual effort estimation = 592.5 Hours to 1,185 Hours

Estimated project duration = 888.75 Hours
