### ISSUE TITLE
White box testing

### ISSUE THREAD

**Issue by Joshuahozy1** [Joshuahozy1/ICT2201_P5-4#112]

**Comment by Joshuahozy1** [comment]
Completed Control flow graph
Pseudocode
basis path

**Comment by Joshuahozy1** [comment]
Pseudocode was implemented for black box testing based on adding of user

**Comment by 2robinxx** [comment]
24/11/2022
Created Control Flow Graph for the Pseudocode

**Comment by tay-en** [comment]
Created the basis path to attempt to test all the functionalities.

**Comment by kennethCWL** [comment]
24/11/2022
Helped out on the creation of Control Flow Graph and pseudocode
