### ISSUE TITLE
Wireframe Enhancement

### ISSUE THREAD

**Issue by Joshuahozy1** [Joshuahozy1/ICT2201_P5-4#115]

**Comment by Joshuahozy1** [comment]
24/11/22
Wireframe made some changes to 
add user page
edit user page
job allocation page for add job
job allocation page for edit job

**Comment by 2robinxx** [comment]
24/11/22
Made changes to:
Login Page (added interactions)
Job rejection page (added interactions)

**Comment by tay-en** [comment]
26/11/22 
Made changes to:
View up to 3 staff availbility in the job allocation page ( font size and aligning)

**Comment by Joshuahozy1** [comment]
26/11/22
Further rectification of frame size was made across all the pages in the UI

**Comment by kennethCWL** [comment]
26/11/2022
Made changes to:
Add/edit availability page
Indicate preference page
