### ISSUE TITLE
M3 Report

### ISSUE THREAD

**Issue by Joshuahozy1** [Joshuahozy1/ICT2201_P5-4#116]

**Comment by Joshuahozy1** [comment]
M3 Report consolidated and checked all sections
26/11/22

**Comment by kennethCWL** [comment]
26/11/2022
Report formatted and aligned the pages with the content page

**Comment by tay-en** [comment]
26/11/2022
Assisted with the report documentation
Added reflection

**Comment by 2robinxx** [comment]
26/11/2022
Added reflection
Edited white-box testing
Editing Wireframe Prototyping
