### ISSUE TITLE
Wireframe

### ISSUE THREAD

**Issue by Joshuahozy1** [Joshuahozy1/ICT2201_P5-4#12]

**Comment by Joshuahozy1** [comment]
Completed Administrator and staff wireframe. 
Includes:
Landing pages
Staff job rejection
Staff availability
Adding of staff 
Management system of staff

**Comment by 2robinxx** [comment]
Completed two pages:
Manager's landing page
Manager's job allocation page for staff

**Comment by tay-en** [comment]
Completed two pages:
Login page
Overall staff/manager account management page
